---
 - name: nginx webserver configure
   hosts: all
   tasks:
         - name: Install Nginx
           yum:
                name: nginx
                state: present

         - name: add index.html file
           ansible.builtin.template:
                src: ./index.html
                dest: /usr/share/nginx/html/index.html

         - name: allow all access to tcp port 80
           ansible.posix.firewalld:
                port: 80/tcp
                zone: public
                state: enabled

         - name: Start Nginx
           service:
                name: nginx
                state: started
